#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-apt', '2.3.0'
mod 'ajcrowe-supervisord',        :git => "https://github.com/ajcrowe/puppet-supervisord.git"
mod 'jfryman-nginx'
mod 'saz-sudo'
mod 'scalecommerce-sc_supervisor',:git => "http://github.com/ScaleCommerce/puppet-sc_supervisor.git"
mod 'scalecommerce-vm_config',    :git => "https://gitlab.scale.sc/scalecommerce/puppet-vm_config.git"
mod 'yo61-logrotate',             :git => "https://github.com/yo61/puppet-logrotate.git"
