
test:ubuntu-14.04:puppet-nginx:
  image: scalecommerce/base:0.6
  script:
  - ./test/install.sh
  - puppet module install puppet-nginx
  - mv ./test/hiera/module.yaml.puppet-nginx  ./test/hiera/module.yaml
  - puppet apply -v test/site.pp
  - inspec exec test/inspec/sc_nginx.rb
  - mv ./test/hiera/override.yaml.puppet-nginx  ./test/hiera/override.yaml
  - puppet apply -v test/site.pp
  - inspec exec test/inspec/sc_nginx.rb
  - inspec exec test/inspec/sc_nginx_override.rb

test:ubuntu-14.04:jfryman-nginx:
  image: scalecommerce/base:0.6
  script:
  - ./test/install.sh
  - puppet module install jfryman-nginx
  - mv ./test/hiera/module.yaml.jfryman-nginx  ./test/hiera/module.yaml
  - puppet apply -v test/site.pp
  - inspec exec test/inspec/sc_nginx.rb
  - mv ./test/hiera/override.yaml.jfryman-nginx  ./test/hiera/override.yaml
  - puppet apply -v test/site.pp
  - inspec exec test/inspec/sc_nginx.rb
  - inspec exec test/inspec/sc_nginx_override.rb

test:ubuntu-16.04:puppet-nginx:
  image: scalecommerce/xenial:1.0
  script:
  - ./test/install.sh
  - puppet module install puppet-nginx
  - mv ./test/hiera/module.yaml.puppet-nginx  ./test/hiera/module.yaml
  - puppet apply -v test/site.pp
  - inspec exec test/inspec/sc_nginx.rb
  - mv ./test/hiera/override.yaml.puppet-nginx  ./test/hiera/override.yaml
  - puppet apply -v test/site.pp
  - inspec exec test/inspec/sc_nginx.rb
  - inspec exec test/inspec/sc_nginx_override.rb

test:ubuntu-16.04:jfryman-nginx:
  image: scalecommerce/xenial:1.0
  script:
  - ./test/install.sh
  - puppet module install jfryman-nginx
  - mv ./test/hiera/module.yaml.jfryman-nginx  ./test/hiera/module.yaml
  - puppet apply -v test/site.pp
  - inspec exec test/inspec/sc_nginx.rb
  - mv ./test/hiera/override.yaml.jfryman-nginx  ./test/hiera/override.yaml
  - puppet apply -v test/site.pp
  - inspec exec test/inspec/sc_nginx.rb
  - inspec exec test/inspec/sc_nginx_override.rb
