image: scalecommerce/xenial:1.11

stages:
  - Puppet 5
  - Puppet 6
  - push2github

16.04:puppet-nginx:puppet5:
  stage: Puppet 5
  image: scalecommerce/xenial:1.11
  script:
    - ./test/install-puppet5.sh
    - ./test/install.sh
    - export PATH=/opt/puppetlabs/bin:$PATH
    - puppet module install puppet-nginx
    - mv ./test/hiera/module.yaml.puppet-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.puppet-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

16.04:puppet-nginx:puppet6:
  stage: Puppet 6
  image: scalecommerce/xenial:1.11
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - export PATH=/opt/puppetlabs/bin:$PATH
    - puppet module install puppet-nginx
    - mv ./test/hiera/module.yaml.puppet-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.puppet-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

push2github:
  stage: push2github
  script:
    - git push --quiet --mirror https://$GITHUB_TOKEN@github.com/ScaleCommerce/puppet-sc_nginx.git
