image: scalecommerce/base:0.6

test:ubuntu-14.04:
  script:
  - ./test/install.sh
  - puppet apply -v test/site.pp
  - puppet apply -v test/site.pp
  - ps ax | grep nginx
  - inspec exec test/inspec/sc_nginx.rb
