stages:
  - Puppet 3
  - Puppet 4
  - Puppet 5
  - push2github

14.04:puppet-nginx:puppet3:
  stage: Puppet 3
  image: scalecommerce/base:0.6
  script:
    - ./test/install.sh
    - puppet module install puppet-nginx
    - mv ./test/hiera/module.yaml.puppet-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.puppet-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

14.04:jfryman-nginx:puppet3:
  stage: Puppet 3
  image: scalecommerce/base:0.6
  script:
    - ./test/install.sh
    - puppet module install jfryman-nginx
    - mv ./test/hiera/module.yaml.jfryman-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.jfryman-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

16.04:puppet-nginx:puppet3:
  stage: Puppet 3
  image: scalecommerce/xenial:1.0
  script:
    - ./test/install.sh
    - puppet module install puppet-nginx
    - mv ./test/hiera/module.yaml.puppet-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.puppet-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

16.04:jfryman-nginx:puppet3:
  stage: Puppet 3
  image: scalecommerce/xenial:1.0
  script:
    - ./test/install.sh
    - puppet module install jfryman-nginx
    - mv ./test/hiera/module.yaml.jfryman-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.jfryman-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

14.04:puppet-nginx:puppet4:
  stage: Puppet 4
  image: scalecommerce/base:0.6
  script:
    - ./test/install-puppet4.sh
    - ./test/install.sh
    - export PATH=/opt/puppetlabs/bin:$PATH
    - puppet module install puppet-nginx
    - mv ./test/hiera/module.yaml.puppet-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.puppet-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

14.04:jfryman-nginx:puppet4:
  stage: Puppet 4
  image: scalecommerce/base:0.6
  script:
    - ./test/install-puppet4.sh
    - ./test/install.sh
    - export PATH=/opt/puppetlabs/bin:$PATH
    - puppet module install jfryman-nginx
    - mv ./test/hiera/module.yaml.jfryman-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.jfryman-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

16.04:puppet-nginx:puppet4:
  stage: Puppet 4
  image: scalecommerce/xenial:1.0
  script:
    - ./test/install-puppet4.sh
    - ./test/install.sh
    - export PATH=/opt/puppetlabs/bin:$PATH
    - puppet module install puppet-nginx
    - mv ./test/hiera/module.yaml.puppet-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.puppet-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

16.04:jfryman-nginx:puppet4:
  stage: Puppet 4
  image: scalecommerce/xenial:1.0
  script:
    - ./test/install-puppet4.sh
    - ./test/install.sh
    - export PATH=/opt/puppetlabs/bin:$PATH
    - puppet module install jfryman-nginx
    - mv ./test/hiera/module.yaml.jfryman-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.jfryman-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

14.04:puppet-nginx:puppet5:
  stage: Puppet 5
  image: scalecommerce/base:0.6
  script:
    - ./test/install-puppet5.sh
    - ./test/install.sh
    - export PATH=/opt/puppetlabs/bin:$PATH
    - puppet module install puppet-nginx
    - mv ./test/hiera/module.yaml.puppet-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.puppet-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

14.04:jfryman-nginx:puppet5:
  stage: Puppet 5
  image: scalecommerce/base:0.6
  script:
    - ./test/install-puppet5.sh
    - ./test/install.sh
    - export PATH=/opt/puppetlabs/bin:$PATH
    - puppet module install jfryman-nginx
    - mv ./test/hiera/module.yaml.jfryman-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.jfryman-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

16.04:puppet-nginx:puppet5:
  stage: Puppet 5
  image: scalecommerce/xenial:1.0
  script:
    - ./test/install-puppet5.sh
    - ./test/install.sh
    - export PATH=/opt/puppetlabs/bin:$PATH
    - puppet module install puppet-nginx
    - mv ./test/hiera/module.yaml.puppet-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.puppet-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

16.04:jfryman-nginx:puppet5:
  stage: Puppet 5
  image: scalecommerce/xenial:1.0
  script:
    - ./test/install-puppet5.sh
    - ./test/install.sh
    - export PATH=/opt/puppetlabs/bin:$PATH
    - puppet module install jfryman-nginx
    - mv ./test/hiera/module.yaml.jfryman-nginx  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - mv ./test/hiera/override.yaml.jfryman-nginx  ./test/hiera/override.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_nginx.rb
    - inspec exec test/inspec/sc_nginx_override.rb

push2github:
  stage: push2github
  script:
    - git push --quiet --mirror https://$GITHUB_TOKEN@github.com/ScaleCommerce/puppet-sc_nginx.git
